server:
  port: 0

logging:
  level:
    root: INFO

bfh:
  endpoints:
    generate: "https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/JAVA"
    fallbackSubmit: "https://bfhldevapigw.healthrx.co.in/hiring/testWebhook/JAVA"
  user:
    name: "Nishan Chakraborty"
    regNo: "22BCE10762"
    email: "nishanchakraborty2022@vitbhopal.ac.in"
